In [370]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
import seaborn as sns
import pickle




from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

from sklearn.impute import KNNImputer



In [371]:
df = pd.read_csv("Sri Lankan CKD Dataset.csv")

In [372]:
a= {"M":1,"F":0}

df["gender"]=df["gender"].map(a)

In [373]:
df = df.drop("cru",axis =1)
df = df.drop("ua",axis =1)
df = df.drop("iron",axis =1)

In [374]:
missing_values_per_row = df.isnull().sum(axis=1)

print("Number of Missing Values per Row:")
print(missing_values_per_row)

Number of Missing Values per Row:
0      6
1      2
2      1
3      2
4      2
      ..
401    4
402    0
403    1
404    4
405    1
Length: 406, dtype: int64


In [375]:
threshold = 10
filtered_data = df[missing_values_per_row <= threshold]

print("\nFiltered DataFrame:")
print(filtered_data)
filtered_data.shape

df = filtered_data.copy()



Filtered DataFrame:
      id   age  weight  gender       cr    al    gl     na    ca    k     cl  \
0      1  72.0   52.00       1   249.43  34.9   NaN  142.0  2.43  5.0  113.0   
1      2  76.0   52.00       1   216.05  41.3   NaN  145.0  2.40  4.7  114.0   
2      3  60.0   80.40       1   155.40  33.7   NaN  135.0  2.00  4.2  103.0   
3      4  65.0   53.40       0   127.50  41.8   NaN  138.0  2.80  4.4  100.0   
4      5  59.0   60.40       1   172.71  39.7   NaN  128.0  2.20  3.6   91.0   
..   ...   ...     ...     ...      ...   ...   ...    ...   ...  ...    ...   
401  402  48.0   48.00       1  1167.62   NaN   NaN  134.0   NaN  4.1   94.0   
402  403  46.0   55.00       1   211.20  37.2  37.9  144.0  2.40  4.3  105.0   
403  404  55.0   54.85       0   164.43  22.2  48.9  129.0   NaN  3.9   97.0   
404  405  84.0   43.90       1   501.71   NaN   NaN  135.0   NaN  5.7   99.0   
405  406  38.0   60.50       1   880.64  38.5  32.1  127.0   NaN  4.1   99.0   

       pr   wbc   

In [376]:
filtered_data.columns

Index(['id', 'age', 'weight', 'gender', 'cr', 'al', 'gl', 'na', 'ca', 'k',
       'cl', 'pr', 'wbc', 'rbc', 'hg', 'plt', 'class'],
      dtype='object')

In [377]:
# # df = df[['cr','age','hg','al','gender','na','gl','ca','class']].copy()
# # df = df[['cr','age','weight','al','gender','k','ca','class']].copy()

# # df = df[['age','hg','al','gender','na','gl','ca','class']].copy()

# # df = df[['cr','age','hg','gender','na','class']].copy()

# # df = df[['age', 'weight', 'gender', 'cr', 'al', 'gl', 'na', 'ca', 'k',
# #        'cl', 'pr', 'wbc', 'rbc', 'hg', 'plt', 'class']].copy()


# df = df[['age','hg','gender','na','ca','class']].copy()

# # df = df[['cr','hg','al','na','gl','ca','class']].copy()

# # df = df[['cr','al','na','gl','ca','cl','k','class','rbc','pr']].copy()



In [378]:
df.drop(columns='id',inplace=True)

In [379]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=14)

# Perform the imputation
df_imputed_1 = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)
df_imputed_1.head()

age  weight  gender      cr    al         gl     na    ca    k     cl  \
0  72.0    52.0     1.0  249.43  34.9  35.721429  142.0  2.43  5.0  113.0   
1  76.0    52.0     1.0  216.05  41.3  38.600000  145.0  2.40  4.7  114.0   
2  60.0    80.4     1.0  155.40  33.7  36.800000  135.0  2.00  4.2  103.0   
3  65.0    53.4     0.0  127.50  41.8  39.271429  138.0  2.80  4.4  100.0   
4  59.0    60.4     1.0  172.71  39.7  33.508571  128.0  2.20  3.6   91.0   

          pr       wbc       rbc         hg         plt  class  
0  48.342857  9.047857  4.312143  12.457143  270.714286    1.0  
1  53.750000  9.850000  3.440000  11.300000  356.000000    1.0  
2  11.600000  9.240000  4.600000   8.400000  329.000000    1.0  
3  76.721429  9.870000  4.320000  11.700000  364.000000    1.0  
4  53.442857  8.930000  4.820000  13.800000  214.000000    1.0

In [380]:
df = df_imputed_1.copy()

In [381]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

# Initialize and fit the model
model = RandomForestClassifier()
model.fit(df.drop(columns=['class']), df['class'])  # Adjust 'target' to your actual target column

# Get feature importances
importances = model.feature_importances_

# Create a DataFrame to associate feature names with their importance
feature_importances = pd.DataFrame({'Feature': df.drop(columns=['class']).columns, 'Importance': importances})

# Sort by importance in descending order
feature_importances = feature_importances.sort_values(by='Importance', ascending=False)
print(feature_importances)


   Feature  Importance
3       cr    0.391064
13      hg    0.141013
12     rbc    0.127357
10      pr    0.082959
7       ca    0.068265
5       gl    0.039216
4       al    0.029813
9       cl    0.029518
6       na    0.018806
0      age    0.017125
11     wbc    0.015910
14     plt    0.012258
8        k    0.012238
1   weight    0.011295
2   gender    0.003163


In [382]:
from xgboost import XGBClassifier
import pandas as pd

# Initialize and fit the model
xgb = XGBClassifier()
xgb.fit(df.drop(columns=['class']), df['class'])  # Adjust 'target' to your actual target column

# Get feature importances
importances = xgb.feature_importances_

# Create a DataFrame to associate feature names with their importance
feature_importances = pd.DataFrame({'Feature': df.drop(columns=['class']).columns, 'Importance': importances})

# Sort by importance in descending order
feature_importances = feature_importances.sort_values(by='Importance', ascending=False)
print(feature_importances)


   Feature  Importance
3       cr    0.688327
12     rbc    0.062222
4       al    0.037059
13      hg    0.030037
1   weight    0.027645
6       na    0.024315
9       cl    0.021074
14     plt    0.020087
0      age    0.019673
7       ca    0.017700
5       gl    0.016436
10      pr    0.016336
8        k    0.009951
11     wbc    0.009140
2   gender    0.000000


In [383]:
from sklearn.inspection import permutation_importance

# Initialize and fit the model (use any model like RandomForestClassifier, etc.)
model = RandomForestClassifier()
model.fit(df.drop(columns=['class']), df['class'])

# Perform permutation importance
result = permutation_importance(model, df.drop(columns=['class']), df['class'], n_repeats=10, random_state=42)

# Create a DataFrame for feature importance
feature_importances = pd.DataFrame({'Feature': df.drop(columns=['class']).columns, 'Importance': result.importances_mean})

# Sort by importance in descending order
feature_importances = feature_importances.sort_values(by='Importance', ascending=False)
print(feature_importances)


   Feature  Importance
3       cr    0.333165
13      hg    0.014684
12     rbc    0.010127
1   weight    0.007848
10      pr    0.006835
7       ca    0.006582
8        k    0.005063
9       cl    0.004810
11     wbc    0.004304
5       gl    0.003797
6       na    0.002025
14     plt    0.002025
4       al    0.001772
0      age    0.000253
2   gender    0.000000


In [384]:
X.isnull().sum()

age         1
weight      4
gender      0
cr          8
al        188
gl        323
na         29
ca        304
k          28
cl        182
pr        319
wbc        29
rbc        32
hg         22
plt        25
dtype: int64

In [385]:
from sklearn.feature_selection import mutual_info_classif
import pandas as pd

# Assuming df is your DataFrame, and 'target' is your target column
X = df.drop(columns=['class'])
y = df['class']

# Calculate mutual information
mi = mutual_info_classif(X, y)

# Create a DataFrame to display the results
mi_df = pd.DataFrame({'Feature': X.columns, 'Mutual Information': mi})

# Sort by mutual information in descending order
mi_df = mi_df.sort_values(by='Mutual Information', ascending=False)
print(mi_df)


   Feature  Mutual Information
3       cr            0.559555
7       ca            0.379461
12     rbc            0.361880
13      hg            0.342068
10      pr            0.341970
9       cl            0.311991
5       gl            0.125275
4       al            0.122019
11     wbc            0.120699
6       na            0.099294
8        k            0.092720
0      age            0.056118
1   weight            0.044173
14     plt            0.033167
2   gender            0.021850


In [386]:
from sklearn.feature_selection import SelectKBest, chi2
import pandas as pd

# Select the best 10 features using the chi-squared test
selector = SelectKBest(chi2, k=10)
X_new = selector.fit_transform(X, y)

# Get the selected features
selected_features = selector.get_support(indices=True)

# Display the selected features
feature_names = X.columns[selected_features]
print("Selected Features:", feature_names)


Selected Features: Index(['age', 'cr', 'al', 'gl', 'na', 'pr', 'wbc', 'rbc', 'hg', 'plt'], dtype='object')


In [387]:
from sklearn.feature_selection import RFECV
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

# Initialize the model (Random Forest in this case)
model = RandomForestClassifier()

# Use RFECV for automatic feature selection
rfecv = RFECV(estimator=model, step=1, cv=5, scoring='accuracy')
rfecv.fit(X, y)

# Get the ranking of features and the number of optimal features
optimal_features = rfecv.support_
ranking = rfecv.ranking_

# Create a DataFrame to show the features and their rankings
rfecv_df = pd.DataFrame({'Feature': X.columns, 'Ranking': ranking, 'Selected': optimal_features})
print(rfecv_df.sort_values(by='Ranking'))


   Feature  Ranking  Selected
3       cr        1      True
13      hg        2     False
12     rbc        3     False
10      pr        4     False
7       ca        5     False
5       gl        6     False
9       cl        7     False
4       al        8     False
14     plt        9     False
0      age       10     False
6       na       11     False
8        k       12     False
11     wbc       13     False
1   weight       14     False
2   gender       15     False


In [389]:
from boruta import BorutaPy
from sklearn.ensemble import RandomForestClassifier

# Initialize Random Forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Initialize Boruta feature selection
boruta_selector = BorutaPy(estimator=model, n_estimators='auto', random_state=42)

# Fit the Boruta selector
boruta_selector.fit(X.values, y.values)

# Get the selected features
selected_features = X.columns[boruta_selector.support_]
print("Selected Features:", selected_features)


Selected Features: Index(['age', 'cr', 'al', 'gl', 'na', 'ca', 'cl', 'pr', 'rbc', 'hg'], dtype='object')


In [342]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=19)

# Perform the imputation
df_imputed_2 = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)
df_imputed_2.head()

age         hg  gender     na    ca  class
0  72.0  12.373684     1.0  142.0  2.43    1.0
1  76.0  11.300000     1.0  145.0  2.40    1.0
2  60.0   8.400000     1.0  135.0  2.00    1.0
3  65.0  11.700000     0.0  138.0  2.80    1.0
4  59.0  13.800000     1.0  128.0  2.20    1.0

In [343]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=15)

# Perform the imputation
df_imputed_3 = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)
df_imputed_3.head()

age         hg  gender     na    ca  class
0  72.0  12.493333     1.0  142.0  2.43    1.0
1  76.0  11.300000     1.0  145.0  2.40    1.0
2  60.0   8.400000     1.0  135.0  2.00    1.0
3  65.0  11.700000     0.0  138.0  2.80    1.0
4  59.0  13.800000     1.0  128.0  2.20    1.0

In [344]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=16)

# Perform the imputation
df_imputed_4 = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)
df_imputed_4.head()

age        hg  gender     na    ca  class
0  72.0  12.41875     1.0  142.0  2.43    1.0
1  76.0  11.30000     1.0  145.0  2.40    1.0
2  60.0   8.40000     1.0  135.0  2.00    1.0
3  65.0  11.70000     0.0  138.0  2.80    1.0
4  59.0  13.80000     1.0  128.0  2.20    1.0

In [345]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=13)

# Perform the imputation
df_imputed_5 = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)
df_imputed_5.head()

age         hg  gender     na    ca  class
0  72.0  12.438462     1.0  142.0  2.43    1.0
1  76.0  11.300000     1.0  145.0  2.40    1.0
2  60.0   8.400000     1.0  135.0  2.00    1.0
3  65.0  11.700000     0.0  138.0  2.80    1.0
4  59.0  13.800000     1.0  128.0  2.20    1.0

In [346]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=10)

# Perform the imputation
df_imputed_6 = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)
df_imputed_6.head()

age     hg  gender     na    ca  class
0  72.0  12.49     1.0  142.0  2.43    1.0
1  76.0  11.30     1.0  145.0  2.40    1.0
2  60.0   8.40     1.0  135.0  2.00    1.0
3  65.0  11.70     0.0  138.0  2.80    1.0
4  59.0  13.80     1.0  128.0  2.20    1.0

In [347]:
# df_imputed = df_imputed.round(1)
X_1 = df_imputed_1.drop(columns='class')
y_1 = df_imputed_1['class']

In [348]:
# df_imputed = df_imputed.round(1)
X_2 = df_imputed_2.drop(columns='class')
y_2 = df_imputed_2['class']

In [349]:
# df_imputed = df_imputed.round(1)
X_3 = df_imputed_3.drop(columns='class')
y_3 = df_imputed_3['class']

In [350]:
# df_imputed = df_imputed.round(1)
X_4 = df_imputed_4.drop(columns='class')
y_4 = df_imputed_4['class']

In [351]:
# df_imputed = df_imputed.round(1)
X_5 = df_imputed_5.drop(columns='class')
y_5 = df_imputed_5['class']

In [352]:
# df_imputed = df_imputed.round(1)
X_6 = df_imputed_6.drop(columns='class')
y_6 = df_imputed_6['class']

In [353]:
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X_1, y_1, test_size=0.2, random_state=42)
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_2, y_2, test_size=0.2, random_state=42)
X_train_3, X_test_3, y_train_3, y_test_3 = train_test_split(X_3, y_3, test_size=0.2, random_state=42)

X_train_4, X_test_4, y_train_4, y_test_4 = train_test_split(X_4, y_4, test_size=0.2, random_state=42)
X_train_5, X_test_5, y_train_5, y_test_5 = train_test_split(X_5, y_5, test_size=0.2, random_state=42)
X_train_6, X_test_6, y_train_6, y_test_6 = train_test_split(X_6, y_6, test_size=0.2, random_state=42)



In [354]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix, cohen_kappa_score, f1_score


# Assuming you have X_train_1, X_train_2, X_train_3, y_train_1, y_train_2, y_train_3, X_test, y_test

# Function to build the model
def build_model(input_dim):
    model = Sequential()
    model.add(Dense(32, input_dim=input_dim, activation='relu'))
    model.add(Dense(8, activation='relu'))
    model.add(Dense(4, activation='relu'))
    # model.add(Dense(4, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# Scale the datasets
scaler_1 = StandardScaler()
scaler_2 = StandardScaler()
scaler_3 = StandardScaler()
scaler_4 = StandardScaler()
scaler_5 = StandardScaler()
scaler_6 = StandardScaler()


# Fit and transform the training data
X_train_1_scaled = scaler_1.fit_transform(X_train_1)
X_train_2_scaled = scaler_2.fit_transform(X_train_2)
X_train_3_scaled = scaler_3.fit_transform(X_train_3)
X_train_4_scaled = scaler_4.fit_transform(X_train_4)
X_train_5_scaled = scaler_5.fit_transform(X_train_5)
X_train_6_scaled = scaler_6.fit_transform(X_train_6)


# Transform the test data using the scalers fitted on respective training sets
X_test_scaled_1 = scaler_1.transform(X_test_1)
X_test_scaled_2 = scaler_2.transform(X_test_2)
X_test_scaled_3 = scaler_3.transform(X_test_3)
X_test_scaled_4 = scaler_4.transform(X_test_4)
X_test_scaled_5 = scaler_5.transform(X_test_5)
X_test_scaled_6 = scaler_6.transform(X_test_6)


# Build and train the models on scaled data
model_1 = build_model(X_train_1_scaled.shape[1])
model_2 = build_model(X_train_2_scaled.shape[1])
model_3 = build_model(X_train_3_scaled.shape[1])
model_4 = build_model(X_train_4_scaled.shape[1])
model_5 = build_model(X_train_5_scaled.shape[1])
model_6 = build_model(X_train_6_scaled.shape[1])


# Train the models
model_1.fit(X_train_1_scaled, y_train_1, epochs=50, batch_size=10, verbose=0)
model_2.fit(X_train_2_scaled, y_train_2, epochs=50, batch_size=10, verbose=0)
model_3.fit(X_train_3_scaled, y_train_3, epochs=50, batch_size=10, verbose=0)
model_4.fit(X_train_4_scaled, y_train_4, epochs=50, batch_size=10, verbose=0)
model_5.fit(X_train_5_scaled, y_train_5, epochs=50, batch_size=10, verbose=0)
model_6.fit(X_train_6_scaled, y_train_6, epochs=50, batch_size=10, verbose=0)

# Get predicted probabilities for each model using scaled test sets
y_pred_prob_1 = model_1.predict(X_test_scaled_1)
y_pred_prob_2 = model_2.predict(X_test_scaled_2)
y_pred_prob_3 = model_3.predict(X_test_scaled_3)
y_pred_prob_4 = model_4.predict(X_test_scaled_4)
y_pred_prob_5 = model_5.predict(X_test_scaled_5)
y_pred_prob_6 = model_6.predict(X_test_scaled_6)


# Averaging the predicted probabilities from all three models
y_pred_prob_avg = (y_pred_prob_1 + y_pred_prob_2 + y_pred_prob_3+y_pred_prob_4+y_pred_prob_5+y_pred_prob_6) / 6

# Convert probabilities to binary labels (threshold = 0.5)
y_pred_final = (y_pred_prob_avg > 0.5).astype("int32")

# Evaluate the accuracy of the final predictions
accuracy = accuracy_score(y_test_1, y_pred_final)
accuracy = accuracy_score(y_test_1, y_pred_final)
recall = recall_score(y_test_1, y_pred_final)
precision = precision_score(y_test_1, y_pred_final)
f1 = f1_score(y_test_1, y_pred_final)
print(f"Final Test Accuracy: {accuracy * 100:.2f}%")
print(f"Recall: {recall:.5f}")
print(f"Precision: {precision:.5f}")
print(f"F1 Score: {f1:.5f}")


c:\Users\MicroChannel\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
Final Test Accuracy: 83.54%
Recall: 0.87037
Precision: 0.88679
F1 Score: 0.87850


In [299]:
# from sklearn.ensemble import StackingClassifier
# from sklearn.datasets import load_iris
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.svm import LinearSVC
# from sklearn.linear_model import LogisticRegression
# from sklearn.preprocessing import StandardScaler
# from sklearn.pipeline import make_pipeline
# from sklearn.ensemble import StackingClassifier

# estimators = [
#     ('rf', RandomForestClassifier(n_estimators=10, random_state=42)),
#     ('xgb', XGBClassifier(random_state=42))  # Replace LinearSVC with XGBClassifier
# ]

# # Define the stacking classifier with a logistic regression as the final estimator
# clf = StackingClassifier(
#     estimators=estimators, final_estimator=LogisticRegression()
# )

# # Fit the stacking classifier and evaluate on the test set
# clf.fit(X_train_1, y_train_1)
# score = clf.score(X_test_1, y_test_1)

# # Display the accuracy score
# print(f"Stacking Classifier Accuracy: {score:.5f}")


In [300]:
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from xgboost import XGBClassifier

clf1 = XGBClassifier()
clf2 = RandomForestClassifier(n_estimators=100, random_state=1)

eclf1 = VotingClassifier(estimators=[
        ('lr', clf1), ('rf', clf2)], voting='hard')
eclf1 = eclf1.fit(X_train_1, y_train_1)

y_pred_1 = eclf1.predict(X_test_1)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test_1, y_pred_1)
recall = recall_score(y_test_1, y_pred_1)
precision = precision_score(y_test_1, y_pred_1)
f1 = f1_score(y_test_1, y_pred_1)
kappa = cohen_kappa_score(y_test_1, y_pred_1)
conf_matrix = confusion_matrix(y_test_1, y_pred_1)

print(f"Accuracy: {accuracy:.5f}")
print(f"Recall: {recall:.5f}")
print(f"Precision: {precision:.5f}")
print(f"F1 Score: {f1:.5f}")
print(f"Cohen's Kappa: {kappa:.5f}")
print("Confusion Matrix:")
print(conf_matrix)


Accuracy: 0.96203
Recall: 0.96296
Precision: 0.98113
F1 Score: 0.97196
Cohen's Kappa: 0.91316
Confusion Matrix:
[[24  1]
 [ 2 52]]


In [301]:
from sklearn.neighbors import KNeighborsClassifier
k = 2 # Number of neighbors
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train_1, y_train_1)

# Predict the labels for the test set
y_pred = knn.predict(X_test_1)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test_1, y_pred)
recall = recall_score(y_test_1, y_pred)
precision = precision_score(y_test_1, y_pred)
conf_matrix = confusion_matrix(y_test_1, y_pred)
kappa = cohen_kappa_score(y_test_1, y_pred)
conf_matrix = confusion_matrix(y_test_1, y_pred)
f1 = f1_score(y_test_1, y_pred)

print(f"Accuracy: {accuracy*100}")
print(f"Recall: {recall*100}")
print(f"Precision: {precision*100}")
print(f"F1 Score: {f1*100}")
print(f"Cohen's Kappa: {kappa}")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 92.40506329113924
Recall: 90.74074074074075
Precision: 98.0
F1 Score: 94.23076923076923
Cohen's Kappa: 0.8316761363636364
Confusion Matrix:
[[24  1]
 [ 5 49]]


In [302]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, confusion_matrix, cohen_kappa_score

# Initialize the models
log_reg = LogisticRegression()
decision_tree = DecisionTreeClassifier()
random_forest = RandomForestClassifier()
adaboost = AdaBoostClassifier()

# Fit the models to the training data
log_reg.fit(X_train_1, y_train_1)
decision_tree.fit(X_train_1, y_train_1)
random_forest.fit(X_train_1, y_train_1)
adaboost.fit(X_train_1, y_train_1)

# Predict using Logistic Regression
y_pred_logreg = log_reg.predict(X_test_1)
# Predict using Decision Tree
y_pred_dt = decision_tree.predict(X_test_1)
# Predict using Random Forest
y_pred_rf = random_forest.predict(X_test_1)
# Predict using AdaBoost
y_pred_adaboost = adaboost.predict(X_test_1)

# Function to calculate and display the evaluation metrics
def evaluate_model(y_test, y_pred, model_name):
    accuracy = accuracy_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    kappa = cohen_kappa_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)

    print(f"--- {model_name} Evaluation ---")
    print(f"Accuracy: {accuracy*100:.2f}%")
    print(f"Recall: {recall*100:.2f}%")
    print(f"Precision: {precision*100:.2f}%")
    print(f"F1 Score: {f1*100:.2f}%")
    print(f"Cohen's Kappa: {kappa:.2f}")
    print("Confusion Matrix:")
    print(conf_matrix)
    print("\n")

# Evaluate each model
evaluate_model(y_test_1, y_pred_logreg, "Logistic Regression")
evaluate_model(y_test_1, y_pred_dt, "Decision Tree")
evaluate_model(y_test_1, y_pred_rf, "Random Forest")
evaluate_model(y_test_1, y_pred_adaboost, "AdaBoost")


c:\Users\MicroChannel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\MicroChannel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


--- Logistic Regression Evaluation ---
Accuracy: 88.61%
Recall: 87.04%
Precision: 95.92%
F1 Score: 91.26%
Cohen's Kappa: 0.75
Confusion Matrix:
[[23  2]
 [ 7 47]]


--- Decision Tree Evaluation ---
Accuracy: 92.41%
Recall: 90.74%
Precision: 98.00%
F1 Score: 94.23%
Cohen's Kappa: 0.83
Confusion Matrix:
[[24  1]
 [ 5 49]]


--- Random Forest Evaluation ---
Accuracy: 96.20%
Recall: 96.30%
Precision: 98.11%
F1 Score: 97.20%
Cohen's Kappa: 0.91
Confusion Matrix:
[[24  1]
 [ 2 52]]


--- AdaBoost Evaluation ---
Accuracy: 93.67%
Recall: 94.44%
Precision: 96.23%
F1 Score: 95.33%
Cohen's Kappa: 0.86
Confusion Matrix:
[[23  2]
 [ 3 51]]




In [184]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D, MaxPooling1D, Flatten
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Assume X and y are your features and labels from tabular data
# Example: X = np.random.rand(1000, 10), y = np.random.randint(0, 2, 1000)

# Split the data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the input data (optional but recommended for neural networks)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train_1)
X_test = scaler.transform(X_test_1)

# Reshape data to fit into a 1D CNN. New shape will be (samples, features, 1) for 1D convolution.
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

# Build the 1D CNN model
model = Sequential()

# 1D convolutional layer with 32 filters and a kernel size of 2
model.add(Conv1D(filters=32, kernel_size=2, activation='relu', input_shape=(X_train.shape[1], 1)))

# Max pooling layer to downsample the data
model.add(MaxPooling1D(pool_size=2))

# Another 1D convolutional layer with 64 filters
model.add(Conv1D(filters=16, kernel_size=2, activation='relu'))

# Flatten the convolution output to feed it into a Dense layer
model.add(Flatten())

# Fully connected layer with 128 units and ReLU activation
model.add(Dense(64, activation='relu'))

# Output layer for binary classification (sigmoid activation)
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train_1, epochs=50, batch_size=32)

# Evaluate the model on the test set
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype("int32")  # Convert probabilities to binary labels

# Calculate accuracy
accuracy = accuracy_score(y_test_1, y_pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%")


c:\Users\MicroChannel\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.4609 - loss: 0.6941
Epoch 2/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7320 - loss: 0.6535
Epoch 3/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7782 - loss: 0.6170 
Epoch 4/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8188 - loss: 0.5690 
Epoch 5/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8032 - loss: 0.5204
Epoch 6/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7910 - loss: 0.4859 
Epoch 7/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8388 - loss: 0.4391
Epoch 8/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8517 - loss: 0.4156
Epoch 9/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8345 - loss: 0.3881  
Epoch 10/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8680 - loss: 0.3656
Epoch 11/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8899 - loss: 0.3119 
Epoch 12/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8

In [157]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Conv1D, MaxPooling1D, Flatten, Add, Activation, BatchNormalization
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Split your data into training and testing sets (replace X and y with your dataset)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the input data (optional but recommended)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train_1)
X_test = scaler.transform(X_test_1)

# Reshape data to fit into a 1D CNN. New shape will be (samples, features, 1) for ResNet-like 1D convolutions.
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

# Define the Residual Block
def residual_block(x, filters, kernel_size=2):
    shortcut = x
    
    # First convolution
    x = Conv1D(filters=filters, kernel_size=kernel_size, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    
    # Second convolution
    x = Conv1D(filters=filters, kernel_size=kernel_size, padding='same')(x)
    x = BatchNormalization()(x)
    
    # Adding shortcut to the output of the second conv layer
    x = Add()([x, shortcut])
    x = Activation('relu')(x)
    
    return x

# Build the ResNet-like model for tabular data
input_layer = Input(shape=(X_train.shape[1], 1))

# Initial Convolution and Pooling layer
x = Conv1D(filters=8, kernel_size=2, padding='same')(input_layer)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = MaxPooling1D(pool_size=2)(x)

# First Residual Block
x = residual_block(x, filters=8)

# Second Residual Block
x = residual_block(x, filters=8)
x = residual_block(x, filters=8)


# Flatten the data for the fully connected layer
x = Flatten()(x)

# Fully connected layer
x = Dense(64, activation='relu')(x)

# Output layer for binary classification (sigmoid activation)
output_layer = Dense(1, activation='sigmoid')(x)

# Define the model
model = Model(inputs=input_layer, outputs=output_layer)

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train_1, epochs=30, batch_size=32)

# Making predictions on the test set
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype("int32")

# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test_1, y_pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%")


Epoch 1/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 14s 15ms/step - accuracy: 0.2855 - loss: 0.8857
Epoch 2/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7322 - loss: 0.5829
Epoch 3/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8530 - loss: 0.4488
Epoch 4/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8986 - loss: 0.3488
Epoch 5/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8790 - loss: 0.3452
Epoch 6/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9023 - loss: 0.3046 
Epoch 7/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9163 - loss: 0.2491
Epoch 8/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8965 - loss: 0.2951
Epoch 9/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9373 - loss: 0.1871 
Epoch 10/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9202 - loss: 0.2272
Epoch 11/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9118 - loss: 0.2335 
Epoch 12/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9419

In [379]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, LSTM, GRU
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Split your data into training and testing sets (replace X and y with your dataset)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the input data (optional but recommended for neural networks)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train_1)
X_test = scaler.transform(X_test_1)

# Reshape the data to fit into an RNN. The new shape will be (samples, timesteps, features).
# We treat the number of features as timesteps in this case.
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))

# Build a simple RNN model
model = Sequential()

# Adding an RNN layer with 50 units (neurons)
# model.add(SimpleRNN(units=50, input_shape=(X_train.shape[1], 1), activation='relu'))
model.add(LSTM(units=50, input_shape=(X_train.shape[1], 1), activation='relu'))


# Fully connected layer
model.add(Dense(64, activation='relu'))

# Output layer for binary classification (sigmoid activation)
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train_1, epochs=20, batch_size=32)

# Making predictions on the test set
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype("int32")  # Convert probabilities to binary labels

# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test_1, y_pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%")


c:\Users\MicroChannel\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - accuracy: 0.5195 - loss: 0.6929
Epoch 2/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8229 - loss: 0.6731 
Epoch 3/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8660 - loss: 0.6506 
Epoch 4/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8467 - loss: 0.6147 
Epoch 5/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8446 - loss: 0.5594 
Epoch 6/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8432 - loss: 0.4632 
Epoch 7/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8120 - loss: 0.4534 
Epoch 8/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8317 - loss: 0.4357 
Epoch 9/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8645 - loss: 0.4076 
Epoch 10/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8384 - loss: 0.4131
Epoch 11/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8533 - loss: 0.4188 
Epoch 12/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0

In [1]:
# Importing necessary libraries
import pandas as pd
from pycaret.classification import setup, compare_models, tune_model, evaluate_model, save_model, load_model

# Load your dataset (replace 'your_dataset.csv' with your actual dataset)
# df = pd.read_csv('your_dataset.csv')

# Setup the PyCaret environment for classification
# In the 'target' argument, provide the column name of the target variable
clf_setup = setup(data=df_imputed_1, target='class', session_id=123, 
                  normalize=True, 
                  train_size=0.8, 
                  feature_selection=True,  # Enable feature selection
                  remove_multicollinearity=True,  # Remove highly correlated features
                  silent=True,  # For automated setup
                  verbose=False)  # Suppress detailed logs

# Compare all classification models and get the best one
best_model = compare_models()

# Optionally, tune the best model for better performance
tuned_model = tune_model(best_model)

# Evaluate the model (this will open an interactive window in Jupyter notebooks)
evaluate_model(tuned_model)

# Predict on the test set
predictions = predict_model(tuned_model)

# Save the model to a file
save_model(tuned_model, 'best_classification_model')

# Load the model (optional, if you want to load it later)
# loaded_model = load_model('best_classification_model')


ModuleNotFoundError: No module named 'pycaret'

In [335]:
from sklearn.ensemble import RandomForestClassifier, VotingClassifier,AdaBoostClassifier
from xgboost import XGBClassifier

clf1 = AdaBoostClassifier()
clf2 = RandomForestClassifier(n_estimators=100, random_state=1)

eclf1 = VotingClassifier(estimators=[
        ('lr', clf1), ('rf', clf2)], voting='hard')
eclf1 = eclf1.fit(X_train_1, y_train_1)

y_pred_1 = eclf1.predict(X_test_1)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test_1, y_pred_1)
recall = recall_score(y_test_1, y_pred_1)
precision = precision_score(y_test_1, y_pred_1)
f1 = f1_score(y_test_1, y_pred_1)
kappa = cohen_kappa_score(y_test_1, y_pred_1)
conf_matrix = confusion_matrix(y_test_1, y_pred_1)

print(f"Accuracy: {accuracy:.5f}")
print(f"Recall: {recall:.5f}")
print(f"Precision: {precision:.5f}")
print(f"F1 Score: {f1:.5f}")
print(f"Cohen's Kappa: {kappa:.5f}")
print("Confusion Matrix:")
print(conf_matrix)


c:\Users\MicroChannel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


Accuracy: 0.78481
Recall: 0.75926
Precision: 0.91111
F1 Score: 0.82828
Cohen's Kappa: 0.54644
Confusion Matrix:
[[21  4]
 [13 41]]


In [61]:
# from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix, cohen_kappa_score, f1_score
# from xgboost import XGBClassifier
# from sklearn.naive_bayes import GaussianNB


# # Initialize XGBoost classifier
# xgb_model_1 = RandomForestClassifier()

# # Fit the model
# xgb_model_1.fit(X_train_1, y_train_1)

# # Predict using the same selected features
# y_pred_1 = xgb_model_1.predict(X_test_1)

# # Calculate evaluation metrics
# accuracy = accuracy_score(y_test_1, y_pred_1)
# recall = recall_score(y_test_1, y_pred_1)
# precision = precision_score(y_test_1, y_pred_1)
# f1 = f1_score(y_test_1, y_pred_1)
# kappa = cohen_kappa_score(y_test_1, y_pred_1)
# conf_matrix = confusion_matrix(y_test_1, y_pred_1)

# # Display the results
# print(f"Accuracy: {accuracy:.5f}")
# print(f"Recall: {recall:.5f}")
# print(f"Precision: {precision:.5f}")
# print(f"F1 Score: {f1:.2f}")
# print(f"Cohen's Kappa: {kappa:.2f}")
# print("Confusion Matrix:")
# print(conf_matrix)


Accuracy: 0.94937
Recall: 0.96296
Precision: 0.96296
F1 Score: 0.96
Cohen's Kappa: 0.88
Confusion Matrix:
[[23  2]
 [ 2 52]]


In [62]:
# from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix, cohen_kappa_score, f1_score
# from sklearn.ensemble import RandomForestClassifier

# # Initialize RandomForest classifier
# rf_model_2 = RandomForestClassifier()

# # Fit the model
# rf_model_2.fit(X_train_2, y_train_2)

# # Predict using the same selected features
# y_pred_2 = rf_model_2.predict(X_test_2)

# # Calculate evaluation metrics
# accuracy = accuracy_score(y_test_2, y_pred_2)
# recall = recall_score(y_test_2, y_pred_2)
# precision = precision_score(y_test_2, y_pred_2)
# f1 = f1_score(y_test_2, y_pred_2)
# kappa = cohen_kappa_score(y_test_2, y_pred_2)
# conf_matrix = confusion_matrix(y_test_2, y_pred_2)

# # Display the results
# print(f"Accuracy: {accuracy:.5f}")
# print(f"Recall: {recall:.5f}")
# print(f"Precision: {precision:.5f}")
# print(f"F1 Score: {f1:.2f}")
# print(f"Cohen's Kappa: {kappa:.2f}")
# print("Confusion Matrix:")
# print(conf_matrix)


In [63]:
# from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix, cohen_kappa_score, f1_score
# from xgboost import XGBClassifier


# # Initialize XGBoost classifier
# xgb_model_2 = RandomForestClassifier()

# # Fit the model
# xgb_model_2.fit(X_train_2, y_train_2)

# # Predict using the same selected features
# y_pred_2 = xgb_model_2.predict(X_test_2)

# # Calculate evaluation metrics
# accuracy = accuracy_score(y_test_2, y_pred_2)
# recall = recall_score(y_test_2, y_pred_2)
# precision = precision_score(y_test_2, y_pred_2)
# f1 = f1_score(y_test_2, y_pred_2)
# kappa = cohen_kappa_score(y_test_2, y_pred_2)
# conf_matrix = confusion_matrix(y_test_2, y_pred_2)

# # Display the results
# print(f"Accuracy: {accuracy:.5f}")
# print(f"Recall: {recall:.5f}")
# print(f"Precision: {precision:.5f}")
# print(f"F1 Score: {f1:.2f}")
# print(f"Cohen's Kappa: {kappa:.2f}")
# print("Confusion Matrix:")
# print(conf_matrix)


Accuracy: 0.96203
Recall: 0.96296
Precision: 0.98113
F1 Score: 0.97
Cohen's Kappa: 0.91
Confusion Matrix:
[[24  1]
 [ 2 52]]


In [64]:
# from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix, cohen_kappa_score, f1_score
# from xgboost import XGBClassifier

# # Initialize XGBoost classifier
# xgb_model_3 = RandomForestClassifier()

# # Fit the model
# xgb_model_3.fit(X_train_3, y_train_3)

# # Predict using the same selected features
# y_pred_3 = xgb_model_3.predict(X_test_3)

# # Calculate evaluation metrics
# accuracy = accuracy_score(y_test_3, y_pred_3)
# recall = recall_score(y_test_3, y_pred_3)
# precision = precision_score(y_test_3, y_pred_3)
# f1 = f1_score(y_test_3, y_pred_3)
# kappa = cohen_kappa_score(y_test_3, y_pred_3)
# conf_matrix = confusion_matrix(y_test_3, y_pred_3)

# # Display the results
# print(f"Accuracy: {accuracy:.5f}")
# print(f"Recall: {recall:.5f}")
# print(f"Precision: {precision:.5f}")
# print(f"F1 Score: {f1:.2f}")
# print(f"Cohen's Kappa: {kappa:.2f}")
# print("Confusion Matrix:")
# print(conf_matrix)


Accuracy: 0.94937
Recall: 0.96296
Precision: 0.96296
F1 Score: 0.96
Cohen's Kappa: 0.88
Confusion Matrix:
[[23  2]
 [ 2 52]]


In [65]:
# from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix, cohen_kappa_score, f1_score
# from xgboost import XGBClassifier

# # Initialize XGBoost classifier
# xgb_model_4 = RandomForestClassifier()

# # Fit the model
# xgb_model_4.fit(X_train_4, y_train_4)

# # Predict using the same selected features
# y_pred_4 = xgb_model_4.predict(X_test_4)

# # Calculate evaluation metrics
# accuracy = accuracy_score(y_test_4, y_pred_4)
# recall = recall_score(y_test_4, y_pred_4)
# precision = precision_score(y_test_4, y_pred_4)
# f1 = f1_score(y_test_4, y_pred_4)
# kappa = cohen_kappa_score(y_test_4, y_pred_4)
# conf_matrix = confusion_matrix(y_test_4, y_pred_4)

# # Display the results
# print(f"Accuracy: {accuracy:.5f}")
# print(f"Recall: {recall:.5f}")
# print(f"Precision: {precision:.5f}")
# print(f"F1 Score: {f1:.2f}")
# print(f"Cohen's Kappa: {kappa:.2f}")
# print("Confusion Matrix:")
# print(conf_matrix)


Accuracy: 0.96203
Recall: 0.96296
Precision: 0.98113
F1 Score: 0.97
Cohen's Kappa: 0.91
Confusion Matrix:
[[24  1]
 [ 2 52]]


In [66]:
# from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix, cohen_kappa_score, f1_score
# from xgboost import XGBClassifier

# # Initialize XGBoost classifier
# xgb_model_5 = RandomForestClassifier()

# # Fit the model
# xgb_model_5.fit(X_train_5, y_train_5)

# # Predict using the same selected features
# y_pred_5 = xgb_model_5.predict(X_test_5)

# # Calculate evaluation metrics
# accuracy = accuracy_score(y_test_5, y_pred_5)
# recall = recall_score(y_test_5, y_pred_5)
# precision = precision_score(y_test_5, y_pred_5)
# f1 = f1_score(y_test_5, y_pred_5)
# kappa = cohen_kappa_score(y_test_5, y_pred_5)
# conf_matrix = confusion_matrix(y_test_5, y_pred_5)

# # Display the results
# print(f"Accuracy: {accuracy:.5f}")
# print(f"Recall: {recall:.5f}")
# print(f"Precision: {precision:.5f}")
# print(f"F1 Score: {f1:.2f}")
# print(f"Cohen's Kappa: {kappa:.2f}")
# print("Confusion Matrix:")
# print(conf_matrix)


Accuracy: 0.96203
Recall: 0.96296
Precision: 0.98113
F1 Score: 0.97
Cohen's Kappa: 0.91
Confusion Matrix:
[[24  1]
 [ 2 52]]


In [67]:
# from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix, cohen_kappa_score, f1_score
# from xgboost import XGBClassifier

# # Initialize XGBoost classifier
# xgb_model_6 = RandomForestClassifier()

# # Fit the model
# xgb_model_6.fit(X_train_6, y_train_6)

# # Predict using the same selected features
# y_pred_6 = xgb_model_6.predict(X_test_6)

# # Calculate evaluation metrics
# accuracy = accuracy_score(y_test_6, y_pred_6)
# recall = recall_score(y_test_6, y_pred_6)
# precision = precision_score(y_test_6, y_pred_6)
# f1 = f1_score(y_test_6, y_pred_6)
# kappa = cohen_kappa_score(y_test_6, y_pred_6)
# conf_matrix = confusion_matrix(y_test_6, y_pred_6)

# # Display the results
# print(f"Accuracy: {accuracy:.5f}")
# print(f"Recall: {recall:.5f}")
# print(f"Precision: {precision:.5f}")
# print(f"F1 Score: {f1:.2f}")
# print(f"Cohen's Kappa: {kappa:.2f}")
# print("Confusion Matrix:")
# print(conf_matrix)


Accuracy: 0.96203
Recall: 0.96296
Precision: 0.98113
F1 Score: 0.97
Cohen's Kappa: 0.91
Confusion Matrix:
[[24  1]
 [ 2 52]]


In [68]:
# import numpy as np

# # Predict probabilities for the training set from both models
# prob_model_1_train = xgb_model_1.predict_proba(X_train_1)
# prob_model_2_train = xgb_model_2.predict_proba(X_train_2)

# # Combine the probabilities for both classes (4 features: 2 from each model)
# X_train_ann = np.hstack((prob_model_1_train, prob_model_2_train))

# # Similarly, get the true labels
# y_train_ann = y_train_1


In [69]:
# prob_model_1_train

In [70]:
# prob_model_2_train


In [71]:
# X_train_ann

In [72]:
# import tensorflow as tf
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense

# # Define the ANN model
# ann_model = Sequential()

# # Input layer (4 inputs from combined probabilities) and hidden layer
# ann_model.add(Dense(8, input_dim=4, activation='relu'))  # 4 input features (2 for each class from both models)

# # Hidden layer (adjust neurons as needed)
# ann_model.add(Dense(4, activation='relu'))

# # Output layer (binary classification)
# ann_model.add(Dense(1, activation='sigmoid'))

# # Compile the model
# ann_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# # Train the model on the combined probability inputs
# ann_model.fit(X_train_ann, y_train_ann, epochs=10, batch_size=10, verbose=1)


In [73]:
# # Predict probabilities for the test set from both models
# prob_model_1_test = xgb_model_1.predict_proba(X_test_1)
# prob_model_2_test = xgb_model_2.predict_proba(X_test_1)

# # Combine the probabilities for test set
# X_test_ann = np.hstack((prob_model_1_test, prob_model_2_test))

# # Use the trained ANN model to predict the classes on the test set
# y_pred_ann = (ann_model.predict(X_test_ann) > 0.5).astype(int)

# # Calculate the accuracy
# accuracy = accuracy_score(y_test_1, y_pred_ann)

# # Display the accuracy
# print(f"ANN Model Accuracy: {accuracy:.5f}")


In [74]:
import numpy as np
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, confusion_matrix, cohen_kappa_score

# Predict probabilities for all test sets
prob_model_1_test = xgb_model_1.predict_proba(X_test_1)
prob_model_2_test = xgb_model_2.predict_proba(X_test_2)
prob_model_3_test = xgb_model_3.predict_proba(X_test_3)
prob_model_4_test = xgb_model_4.predict_proba(X_test_4)
prob_model_5_test = xgb_model_5.predict_proba(X_test_5)
prob_model_6_test = xgb_model_6.predict_proba(X_test_6)

# Get the probabilities for class 1 (positive class) from all models
probs_class_1 = np.vstack([
    prob_model_1_test[:, 1],  # Class 1 probability for model 1
    prob_model_2_test[:, 1],  # Class 1 probability for model 2
    prob_model_3_test[:, 1],  # Class 1 probability for model 3
    prob_model_4_test[:, 1],  # Class 1 probability for model 4
    prob_model_5_test[:, 1],  # Class 1 probability for model 5
    prob_model_6_test[:, 1]   # Class 1 probability for model 6
])

# Perform voting (count how many models predict class 1)
votes_class_1 = np.sum(probs_class_1 > 0.5, axis=0)  # Count the number of models predicting class 1

# Majority voting: if 3 or more models predict class 1, the final prediction is class 1
y_pred_voted = (votes_class_1 >= 3).astype(int)

# True labels (assuming you have the labels for the test set)
# Replace y_test with the actual labels for your data
y_test = y_test_1  # or the combined test labels

# Calculate accuracy and other metrics
accuracy = accuracy_score(y_test, y_pred_voted)
recall = recall_score(y_test, y_pred_voted)
precision = precision_score(y_test, y_pred_voted)
f1 = f1_score(y_test, y_pred_voted)
kappa = cohen_kappa_score(y_test, y_pred_voted)
conf_matrix = confusion_matrix(y_test, y_pred_voted)

# Display the results
print(f"Accuracy: {accuracy:.5f}")
print(f"Recall: {recall:.5f}")
print(f"Precision: {precision:.5f}")
print(f"F1 Score: {f1:.5f}")
print(f"Cohen's Kappa: {kappa:.5f}")
print("Confusion Matrix:")
print(conf_matrix)


Accuracy: 0.96203
Recall: 0.96296
Precision: 0.98113
F1 Score: 0.97196
Cohen's Kappa: 0.91316
Confusion Matrix:
[[24  1]
 [ 2 52]]


In [119]:
# import numpy as np
# from sklearn.metrics import accuracy_score

# # Predict probabilities for both models on the test set
# prob_model_1_test = xgb_model_1.predict_proba(X_test_1)
# prob_model_2_test = xgb_model_2.predict_proba(X_test_2)
# prob_model_3_test = xgb_model_3.predict_proba(X_test_3)
# prob_model_4_test = xgb_model_4.predict_proba(X_test_4)
# prob_model_5_test = xgb_model_5.predict_proba(X_test_5)
# prob_model_6_test = xgb_model_6.predict_proba(X_test_6)


# # Sum the probabilities from both models
# combined_prob_test = np.add(prob_model_1_test, prob_model_2_test)

# # Predict the class with the highest combined probability
# y_pred_combined = np.argmax(combined_prob_test, axis=1)

# # Calculate accuracy
# accuracy = accuracy_score(y_test_1, y_pred_combined)

# # Display the accuracy
# print(f"Combined Model Accuracy: {accuracy:.5f}")


Combined Model Accuracy: 0.94937


In [62]:
prob_model_1_test

array([[9.84378099e-01, 1.56219145e-02],
       [1.85494423e-02, 9.81450558e-01],
       [9.99695301e-01, 3.04717280e-04],
       [1.89132094e-02, 9.81086791e-01],
       [3.32885981e-03, 9.96671140e-01],
       [9.99726951e-01, 2.73036188e-04],
       [3.01241875e-04, 9.99698758e-01],
       [9.96275008e-01, 3.72498110e-03],
       [9.99452174e-01, 5.47835545e-04],
       [6.32089376e-03, 9.93679106e-01],
       [9.17315483e-04, 9.99082685e-01],
       [9.99397516e-01, 6.02512038e-04],
       [9.97153282e-01, 2.84669315e-03],
       [8.65811110e-03, 9.91341889e-01],
       [8.73956859e-01, 1.26043156e-01],
       [5.61475754e-05, 9.99943852e-01],
       [3.87692451e-02, 9.61230755e-01],
       [9.99338925e-01, 6.61073427e-04],
       [9.98216629e-01, 1.78335793e-03],
       [9.99708533e-01, 2.91469536e-04],
       [2.61767507e-02, 9.73823249e-01],
       [3.25051248e-01, 6.74948752e-01],
       [1.21301413e-03, 9.98786986e-01],
       [2.03496218e-02, 9.79650378e-01],
       [2.418160

In [64]:
prob_model_2_test

array([[9.7494936e-01, 2.5050610e-02],
       [5.8109343e-02, 9.4189066e-01],
       [9.9956602e-01, 4.3400822e-04],
       [5.9127808e-04, 9.9940872e-01],
       [4.4577718e-03, 9.9554223e-01],
       [9.9926358e-01, 7.3641521e-04],
       [2.0319223e-04, 9.9979681e-01],
       [9.9943835e-01, 5.6164118e-04],
       [9.9941945e-01, 5.8052863e-04],
       [4.5448542e-03, 9.9545515e-01],
       [9.9891424e-04, 9.9900109e-01],
       [9.9628550e-01, 3.7145182e-03],
       [9.9960577e-01, 3.9421261e-04],
       [4.5821667e-03, 9.9541783e-01],
       [8.9666307e-01, 1.0333694e-01],
       [1.6021729e-04, 9.9983978e-01],
       [1.8241823e-02, 9.8175818e-01],
       [9.9916446e-01, 8.3556224e-04],
       [9.9932981e-01, 6.7021797e-04],
       [9.9946260e-01, 5.3742004e-04],
       [2.0649844e-01, 7.9350156e-01],
       [5.5626631e-02, 9.4437337e-01],
       [3.2126904e-04, 9.9967873e-01],
       [4.7194362e-03, 9.9528056e-01],
       [3.7539005e-04, 9.9962461e-01],
       [6.0131550e-03, 9.

In [42]:
y_pred_2

array([0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1])

In [43]:
y_pred_1

array([0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1])

In [45]:
np.array(y_test_2)

array([0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1.,
       0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1.])

In [11]:
# Import necessary libraries
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# # Generating a synthetic dataset with 8 features and 396 samples for demonstration
# # In practice, you would load your actual dataset here
# np.random.seed(42)
# X = np.random.rand(396, 8)  # 396 samples, 8 features
# y = np.random.randint(0, 2, 396)  # Binary target (0 or 1)

# # Splitting the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Standardizing the features (helps with model convergence)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Building a simple ANN model
model = Sequential()

# Input layer with 8 features and a hidden layer with 16 neurons (ReLU activation)
model.add(Dense(16, input_dim=8, activation='relu'))

# Adding a second hidden layer with 8 neurons (ReLU activation)
model.add(Dense(8, activation='relu'))

# Output layer for binary classification (Sigmoid activation)
model.add(Dense(1, activation='sigmoid'))

# Compiling the model with binary cross-entropy loss and Adam optimizer
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Training the model (50 epochs, batch size of 10)
model.fit(X_train, y_train, epochs=100, batch_size=10, validation_data=(X_test, y_test))

# Making predictions on the test set
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype("int32")  # Convert probabilities to binary labels (0 or 1)

# Evaluating the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy * 100:.5f}%")


c:\Users\MicroChannel\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.6430 - loss: 0.6454 - val_accuracy: 0.6555 - val_loss: 0.6292
Epoch 2/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7808 - loss: 0.5887 - val_accuracy: 0.7983 - val_loss: 0.5692
Epoch 3/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8942 - loss: 0.4984 - val_accuracy: 0.8487 - val_loss: 0.5102
Epoch 4/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8833 - loss: 0.4531 - val_accuracy: 0.8739 - val_loss: 0.4501
Epoch 5/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8920 - loss: 0.3967 - val_accuracy: 0.8824 - val_loss: 0.3958
Epoch 6/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9506 - loss: 0.3155 - val_accuracy: 0.8824 - val_loss: 0.3564
Epoch 7/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2776 - val_accuracy: 0.8908 - val_loss: 0.3303
Epoch 8/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9043 - loss: 0.2743 - val_accuracy: 0.8908 - 

In [12]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix, cohen_kappa_score, f1_score

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the parameter grid for Logistic Regression
param_grid = {
    'penalty': ['l1', 'l2', 'elasticnet', 'none'],
    'C': np.logspace(-4, 4, 20),
    'solver': ['liblinear', 'saga']  # solvers that support l1, l2, and elasticnet penalties
}

# param_grid = {
#     'penalty': ['l1'],
#     'C': [0.0885],
#     'solver': ['liblinear']  # solvers that support l1, l2, and elasticnet penalties
# }

# Initialize the Logistic Regression classifier
logreg = LogisticRegression()

# Initialize GridSearchCV with cross-validation
grid_search = GridSearchCV(logreg, param_grid, cv=5, scoring='accuracy')

# Fit the model with GridSearchCV to find the best parameters
grid_search.fit(X_train, y_train)

# Get the optimal parameters
best_params = grid_search.best_params_
print(f"The optimal parameters are: {best_params}")

# Train the Logistic Regression classifier with the optimal parameters
logreg_optimal = LogisticRegression(**best_params)
logreg_optimal.fit(X_train, y_train)

# Predict the labels for the test set
y_pred = logreg_optimal.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
kappa = cohen_kappa_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Display the results
print(f"Accuracy: {accuracy:.5f}")
print(f"Recall: {recall:.2f}")
print(f"Precision: {precision:.5f}")
print(f"F1 Score: {f1:.2f}")
print(f"Cohen's Kappa: {kappa:.2f}")
print("Confusion Matrix:")
print(conf_matrix)


c:\Users\MicroChannel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\MicroChannel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\MicroChannel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\MicroChannel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\MicroChannel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The ma

The optimal parameters are: {'C': 29.763514416313132, 'penalty': 'l2', 'solver': 'liblinear'}
Accuracy: 0.86076
Recall: 0.83
Precision: 0.95745
F1 Score: 0.89
Cohen's Kappa: 0.70
Confusion Matrix:
[[23  2]
 [ 9 45]]


c:\Users\MicroChannel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
400 fits failed out of a total of 800.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
100 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\MicroChannel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\MicroChannel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Fil

In [24]:
# selected_features = ['feature1', 'feature2', 'feature3']  # Only use these features
# X_train_selected = X_train[selected_features]
# X_test_selected = X_test[selected_features]

# Train Random Forest on the selected features
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)

# Predict using the same selected features
y_pred = rf_model.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
kappa = cohen_kappa_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Display the results
print(f"Accuracy: {accuracy:.5f}")
print(f"Recall: {recall:.5f}")
print(f"Precision: {precision:.5f}")
print(f"F1 Score: {f1:.2f}")
print(f"Cohen's Kappa: {kappa:.2f}")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.96203
Recall: 0.96296
Precision: 0.98113
F1 Score: 0.97
Cohen's Kappa: 0.91
Confusion Matrix:
[[24  1]
 [ 2 52]]


In [43]:
df.columns

Index(['age', 'weight', 'gender', 'cr', 'al', 'gl', 'na', 'ca', 'k', 'cl',
       'pr', 'wbc', 'rbc', 'hg', 'plt', 'class'],
      dtype='object')

In [135]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=14)

# Perform the imputation
df_imputed = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)
df_imputed.head()

cr   age         hg    al  gender     na         gl    ca  class
0  249.43  72.0  12.457143  34.9     1.0  142.0  35.721429  2.43    1.0
1  216.05  76.0  11.300000  41.3     1.0  145.0  36.107143  2.40    1.0
2  155.40  60.0   8.400000  33.7     1.0  135.0  36.158571  2.00    1.0
3  127.50  65.0  11.700000  41.8     0.0  138.0  32.994286  2.80    1.0
4  172.71  59.0  13.800000  39.7     1.0  128.0  37.908571  2.20    1.0

In [136]:
# df_imputed = df_imputed.round(1)
X = df_imputed.drop(columns='class')
y = df_imputed['class']

In [138]:
# Import necessary libraries
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# # Generating a synthetic dataset with 8 features and 396 samples for demonstration
# # In practice, you would load your actual dataset here
# np.random.seed(42)
# X = np.random.rand(396, 8)  # 396 samples, 8 features
# y = np.random.randint(0, 2, 396)  # Binary target (0 or 1)

# # Splitting the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Standardizing the features (helps with model convergence)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Building a simple ANN model
model = Sequential()

# Input layer with 8 features and a hidden layer with 16 neurons (ReLU activation)
model.add(Dense(16, input_dim=8, activation='relu'))

# Adding a second hidden layer with 8 neurons (ReLU activation)
model.add(Dense(8, activation='relu'))

# Output layer for binary classification (Sigmoid activation)
model.add(Dense(1, activation='sigmoid'))

# Compiling the model with binary cross-entropy loss and Adam optimizer
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Training the model (50 epochs, batch size of 10)
model.fit(X_train, y_train, epochs=100, batch_size=10, validation_data=(X_test, y_test))

# Making predictions on the test set
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype("int32")  # Convert probabilities to binary labels (0 or 1)

# Evaluating the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%")


Epoch 1/100


c:\Users\MicroChannel\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


28/28 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.6138 - loss: 0.6558 - val_accuracy: 0.7563 - val_loss: 0.5818
Epoch 2/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7768 - loss: 0.5820 - val_accuracy: 0.8235 - val_loss: 0.5126
Epoch 3/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8659 - loss: 0.5010 - val_accuracy: 0.8487 - val_loss: 0.4510
Epoch 4/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8530 - loss: 0.4323 - val_accuracy: 0.8571 - val_loss: 0.3948
Epoch 5/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9045 - loss: 0.3857 - val_accuracy: 0.8908 - val_loss: 0.3516
Epoch 6/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9086 - loss: 0.3406 - val_accuracy: 0.8908 - val_loss: 0.3237
Epoch 7/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9437 - loss: 0.2619 - val_accuracy: 0.8992 - val_loss: 0.3044
Epoch 8/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9507 - loss: 0.2229 - val_accuracy: 0.8992 - val_loss: 0.

In [113]:
# df_imputed = df_imputed.drop(columns='id')

In [114]:
# df_imputed = df_imputed.round(1)
X = df_imputed.drop(columns='class')
y = df_imputed['class']

In [115]:
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# from sklearn.inspection import permutation_importance


In [116]:
# from sklearn.feature_selection import RFE

# model = LogisticRegression(max_iter=1000)

# # Use RFE to select top 2 features
# rfe = RFE(model, n_features_to_select=2)
# fit = rfe.fit(X, y)

# # Print selected features
# selected_features = [feature for feature, selected in zip(X.columns, fit.support_) if selected]
# print(f"Selected Features: {selected_features}")

# # Rank all features
# ranking = pd.DataFrame({'Feature': X.columns, 'Ranking': fit.ranking_})
# print(ranking.sort_values(by='Ranking'))

In [117]:
# # d = df_imputed.round(1)
# d = df_imputed[['ca','gender','hg','al','na','class','cr']]

# X = d.drop(columns='class')
# y = d['class']

In [118]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Train the XGBoost Classifier
from xgboost import XGBClassifier

model = XGBClassifier()
model.fit(X_train, y_train)

# Step 4: Evaluate the model
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")



Model Accuracy: 0.86


In [119]:
# X_train

In [120]:
X_test

age    hg         al  gender          na         gl        ca
78   45.0  11.7  36.371429     0.0  133.000000  35.178571  2.195714
371  63.0  10.9  35.700000     0.0  141.000000  32.842857  2.200000
248  45.0  15.0  36.120000     0.0  141.000000  43.600000  2.128571
55   27.0  13.2  38.500000     1.0  139.428571  38.335714  2.390714
390  48.0  13.5  35.650000     1.0  134.000000  35.792857  2.234286
..    ...   ...        ...     ...         ...        ...       ...
364  34.0  10.1  32.900000     1.0  134.000000  20.200000  2.470000
82   61.0  10.8  35.370000     0.0  134.142857  31.065714  1.990714
114  52.0   9.5  30.700000     1.0  125.000000  35.500000  2.190714
3    65.0  11.7  41.800000     0.0  138.000000  32.487143  2.800000
18   68.0  13.1  36.520000     1.0  133.000000  28.194286  2.113571

[79 rows x 7 columns]

In [121]:
y_test

78     0.0
371    1.0
248    0.0
55     1.0
390    1.0
      ... 
364    1.0
82     0.0
114    1.0
3      1.0
18     1.0
Name: class, Length: 79, dtype: float64

In [128]:
y_pred

array([1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1])

In [122]:
# x_ = np.array([716.230,60.0, 84.0,38.800000,	1.0,121.0,31.042857,2.100000,77.000000,4.5])
# x_ = x_.reshape(1, -1)

# # single_instance = np.array([4.5, 2.3, 1.3, 0.2, 3.1])

# # # Reshape it into a 2D array
# # single_instance_reshaped = single_instance.reshape(1, -1)

In [123]:
# import pickle

# # Load the saved XGBoost model
# with open("model_folder/xgboost_ckd_model.pkl", "rb") as file:
#     m = pickle.load(file)

In [124]:
# y_ = m.predict(x_)
# y_

In [125]:
# y_

In [126]:
y_test

78     0.0
371    1.0
248    0.0
55     1.0
390    1.0
      ... 
364    1.0
82     0.0
114    1.0
3      1.0
18     1.0
Name: class, Length: 79, dtype: float64

In [127]:
import os
folder_name = "model_folder"
if not os.path.exists(folder_name):
    os.makedirs(folder_name)
    print(f"Folder '{folder_name}' created.")

# Step 6: Save the model in the new folder
# model_path = os.path.join(folder_name, 'xgboost_ckd_model_no_alglca.pkl')
# model_path = os.path.join(folder_name, 'xgboost_ckd_model.pkl')
model_path = os.path.join(folder_name, 'xgboost_ckd_model_no_scr.pkl')


with open(model_path, 'wb') as file:
    pickle.dump(model, file)

print(f"Model saved as {model_path}")

Model saved as model_folder\xgboost_ckd_model_no_scr.pkl
